version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: aseef-dev
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo 'logging into ECR'
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - env

  build:
    commands:
      - echo build start at $(date)
      - echo building docker imagge
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo build completed on $(date)
      - echo pushing images
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
